name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'

inputs: 
  spec_file:
    description: 'path to the spec file'
    required: true
    default: '*.spec'
  sources_dir:
    description: 'path to the SOURCES directory'
    required: true
    default: 'SOURCES'

outputs:
  rpm_dir_path:
    description: 'path to RPMS directory'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.spec_file }}
    - ${{ inputs.sources_dir }}