name: Release CI
on:
  push:
    tags:
      - 'v*.*.*'
env:
  VERSION: $(echo $GITHUB_REF | cut -d'-' -f1 | cut -c12-)

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install mono
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update
          sudo apt-get install -y mono-devel nuget

      - name: Build tldr-sharp
        run: |
          nuget restore
          msbuild tldr-sharp -t:Rebuild -p:TargetFrameworks=net461 -p:Configuration=Release -p:AllowedReferenceRelatedFileExtensions=none

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: tldr-sharp/bin/
          key: ${{ runner.os }}-build-${{ github.sha }}
          
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: tldr-sharp/bin/
          key: ${{ runner.os }}-build-${{ github.sha }}
      - run: bash scripts/test.sh
          

  create_setup:
    runs-on: ubuntu-20.04
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: tldr-sharp/bin/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Copy build output
        run: |
          cp -r tldr-sharp/bin/Release/net461 scripts/windows/release
          cp scripts/windows/sqlite3.dll scripts/windows/release/
          mv scripts/windows/release/net461/tldr-sharp.exe scripts/windows/release/tldr.exe
          mv scripts/windows/release/net461/tldr-sharp.exe.config scripts/windows/release/tldr.exe.config

      - name: Download EnVar plugin for NSIS
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}

      - name: Extract EnVar plugin
        run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/envar_plugin.zip"

      - name: Install makensis
        run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-pluginapi

      - name: Set Plugin permissions
        run: sudo chown -R $(whoami) /usr/share/nsis/Plugins/

      - name: Set tldr-sharp version
        run: sed -i "s/VERSION_PLACEHOLDER/${{ env.VERSION }}.0/g" "scripts/windows/install.nsi"

      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: scripts/windows/install.nsi
          additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins

      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          files: scripts/windows/tldr-sharp_setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_deb:
    runs-on: ubuntu-20.04
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: tldr-sharp/bin/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Prepare directory
        run: |
          HOME_PATH=$(pwd)
          pushd tldr-sharp/bin/Release/net461
          find . -not -name "*.exe" -type f -exec install -Dm 644 '{}' "${HOME_PATH}/.debpkg/usr/lib/tldr-sharp/{}" \;
          find . -name '*.exe' -type f -exec install -Dm 755 '{}' "${HOME_PATH}/.debpkg/usr/lib/tldr-sharp/{}" \;
          popd
          install -Dm755 "scripts/debian/tldr-sharp" ".debpkg/usr/bin/tldr-sharp"
          install -Dm644 "scripts/debian/control" ".debpkg/DEBIAN/control"
          install -Dm755 "scripts/debian/postinst" ".debpkg/DEBIAN/postinst"
          install -Dm755 "scripts/debian/prerm" ".debpkg/DEBIAN/prerm"
          sed -i "s/VERSION_PLACEHOLDER/${{ env.VERSION }}/g" ".debpkg/DEBIAN/control"

      - name: Build Debian package
        run: fakeroot dpkg-deb --build ".debpkg" "tldr-sharp.deb"

      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          files: tldr-sharp.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_archives:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: tldr-sharp/bin/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Create Linux archive
        run: |
          tar czf tldr-sharp_linux.tar.gz -C tldr-sharp/bin/Release/net461/ .

      - name: Create Windows archive
        run: |
          cp scripts/windows/sqlite3.dll tldr-sharp/bin/Release/net461/
          pushd tldr-sharp/bin/Release/net461/
          zip -r ../../../tldr-sharp_windows.zip .
          popd

      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tldr-sharp_linux.tar.gz
            tldr-sharp_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}